"""add_table_user

Revision ID: 89e2e510ce55
Revises: d5f5f8a09616
Create Date: 2020-10-29 18:09:55.965296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e2e510ce55'
down_revision = 'd5f5f8a09616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('set_at', sa.DateTime(), nullable=False),
    sa.Column('name_type', sa.Enum('USERNAME', 'NICKNAME', name='nametype'), nullable=False),
    sa.Column('name_before', sa.String(), nullable=False),
    sa.Column('name_after', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name')
    # ### end Alembic commands ###
