"""add_user_table

Revision ID: a4ce5df2cbf8
Revises: b5e7eda949c2
Create Date: 2020-10-31 18:21:30.103130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ce5df2cbf8'
down_revision = 'b5e7eda949c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'avatar', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'name', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'name', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'avatar', type_='foreignkey')
    op.drop_table('user')
    # ### end Alembic commands ###
