"""add_cascade_to_message_attachment

Revision ID: b5e7eda949c2
Revises: 89e2e510ce55
Create Date: 2020-10-31 18:10:05.942021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e7eda949c2'
down_revision = '89e2e510ce55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('filename', sa.String(), nullable=False))
    op.alter_column('attachment', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('attachment', 'path')
    op.drop_column('avatar', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatar', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('attachment', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('attachment', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('attachment', 'filename')
    # ### end Alembic commands ###
