"""Optional Names

Revision ID: dfc9f42091cf
Revises: 30b572984293
Create Date: 2021-01-09 15:32:14.987167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc9f42091cf'
down_revision = '30b572984293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('name', 'name_after',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('name', 'name_before',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('name', 'name_before',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('name', 'name_after',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
