version: "3.8"
services:
  db:
    image: postgres:13
    env_file:
      - ./db/db.env
    volumes:
      - db:/var/lib/postgresql/data/
    restart: always
  bot:
    build: ./bot
    env_file:
      - ./bot/bot.env
      - ./db/db.env
    environment:
      DB_IP: db
      DEV: 0
    secrets:
      - bot-token
    volumes:
      - bot_config:/usr/src/bot/config
      - bot_files:/usr/src/bot/files
    depends_on:
      - db
    restart: always
volumes:
  db:
  bot_config:
  bot_files:
secrets:
  bot-token:
    file: ./bot/token.txt
